### PR TITLE
Patch the library header to correctly describe the API/ABI of the library regardless of wheter the UNICODE preprocessor is defined

### PR DESCRIPTION
**Pull request by saraedum**
The build 0 was built without wstring support. Apparently, at the time,
the Windows compiler did not define UNICODE. Now that's the default in
conda-forge's setup.
Before this commit, when building against tiny-process-library, the
builds fail because the headers declare a wstring interface. However,
the built library .lib/.dll files only provide the string interface. This
happens e.g., here: https://github.com/conda-forge/staged-recipes/pull/16209

```
cppast.lib(libclang_parser.cpp.obj) : error LNK2019: unresolved external symbol "public: __cdecl TinyProcessLib::Process::Process(class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > const &,class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > const &,class std::function<void __cdecl(char const *,unsigned __int64)>,class std::function<void __cdecl(char const *,unsigned __int64)>,bool,struct TinyProcessLib::Config const &)" (??0Process@TinyProcessLib@@qeaa@AEBV?$basic_string@_WU?$char_traits@_W@std@@v?$allocator@_W@2@@std@@0V?$function@$$A6AXPEBD_K@Z@3@1_NAEBUConfig@1@@z) referenced in function "void __cdecl `anonymous namespace'::add_default_include_dirs(class cppast::libclang_compile_config &)" (?add_default_include_dirs@?A0xf4504779@@YAXAEAVlibclang_compile_config@cppast@@@z)
cppast.lib(preprocessor.cpp.obj) : error LNK2001: unresolved external symbol "public: __cdecl TinyProcessLib::Process::Process(class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > const &,class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > const &,class std::function<void __cdecl(char const *,unsigned __int64)>,class std::function<void __cdecl(char const *,unsigned __int64)>,bool,struct TinyProcessLib::Config const &)" (??0Process@TinyProcessLib@@qeaa@AEBV?$basic_string@_WU?$char_traits@_W@std@@v?$allocator@_W@2@@std@@0V?$function@$$A6AXPEBD_K@Z@3@1_NAEBUConfig@1@@z)
```

So we rebuild tiny-process-library to get the wstring interface on
Windows also in the built library.

Note that this breaks any packages that depend on tiny-process-library
as a runtime dependency on Windows. They would also have to be rebuilt. However, at
least in the linux-64 metadata, there is no package that depends on
tiny-process-library. (Otherwise such a change would warrant a PR to the
repodata-patches repository.)

### CODE REVIEW

**Comment by saraedum** [comment]
@conda-forge-admin, please rerender

**Comment by saraedum** [comment]
@traversaro please have a look. All I did is bump the build number and add myself as a maintainer.

**Comment by traversaro** [comment]
Hi @saraedum , I will check this in depth on (CEST) Monday morning, currently I am far from a PC. However, this feedstock is currently used in many builds of gazebo on win-64, so an ABI breakage would need to be accounted for.

**Comment by saraedum** [comment]
@traversaro ah, thanks for pointing that out. Then we should probably find a better solution here.

**Comment by saraedum** [comment]
In gazebo builds you get away with using `std::string`. I'll have to dig a bit deeper to find out what's different in that build so that `UNICODE` is not set.

**Comment by saraedum** [comment]
Apparently, the unicode support is enabled by including this in the cmake setup:

```
include_directories(${LLVM_INCLUDE_DIRS})
separate_arguments(LLVM_DEFINITIONS_LIST NATIVE_COMMAND ${LLVM_DEFINITIONS})
add_definitions(${LLVM_DEFINITIONS_LIST})
```

In any case, this PR won't change anything to the tiny-process-library. The library will still build without unicode support (which seems more sane to me actually.)

Sorry for the noise here. I guess this PR can be closed. Or it can be merged if you would like to update tho compilers that are used.

**Comment by traversaro** [comment]
Thanks for the debug! I need to check further, but I have the impression that our problem is that the header installed by this package does not describe unambiguously the ABI with which we compiled it, and probably we should fix this. I will check this tomorrow.

**Comment by saraedum** [comment]
> Thanks for the debug! I need to check further, but I have the impression that our problem is that the header installed by this package does not describe unambiguously the ABI with which we compiled it, and probably we should fix this. I will check this tomorrow.

Yes, I think that's exactly what is happening here.

**Comment by traversaro** [comment]
@saraedum I tried to do a quick fix that should work fine for conda-forge packaging in https://github.com/conda-forge/tiny-process-library-feedstock/pull/1/commits/f66185205c629fb1be9e034c5b9029338284c3a6 and https://github.com/conda-forge/tiny-process-library-feedstock/pull/1/commits/5d2a9f8fa83e9a2ad4a52bbee710fad8b5848567 . Integrating a proper fix upstream will take more time, but in the mean time this patch should fix your problem.

**Comment by traversaro** [comment]
I also modified the PR title to describe the content.

**Comment by saraedum** [comment]
Thanks. Looks good to me.

**Review by traversaro — APPROVED** [review]

**Comment by traversaro** [comment]
> Thanks. Looks good to me.

Great, thanks!

**Pull request merged**
